### ISSUE TITLE
SpiderFoot - Out-Of-Date

### ISSUE THREAD

**Issue by MatheusViGo** [ParrotSec/desktop-base#1]
Current version in repository is 2.5 and the latest version is 2.8.
#http://www.spiderfoot.net/news/spiderfoot-2-8-0/

**Comment by PalinuroSec** [comment]
we are working on that, we were searching for a package maintainer for a while without any success but now we have probably found one

**Comment by MatheusViGo** [comment]
Cool, thanks !
